-- MySQL Script generated by MySQL Workbench
-- Sat Oct 12 17:30:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sensor_network_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sensor_network_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sensor_network_db` DEFAULT CHARACTER SET utf8 ;
USE `sensor_network_db` ;

-- -----------------------------------------------------
-- Table `sensor_network_db`.`temperature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensor_network_db`.`temperature` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `temp` FLOAT(6,2) NOT NULL,
  `creation_date` TIMESTAMP NULL DEFAULT NOW(),
  `created_by` VARCHAR(45) NOT NULL DEFAULT 'system',
  `is_deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
